/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.75
 * Generated at: 2023-08-31 12:04:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class regist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1687183239433L));
    _jspx_dependants.put("/WEB-INF/views/./include/footer.jsp", Long.valueOf(1691822901646L));
    _jspx_dependants.put("jar:file:/C:/Users/hanarae/Desktop/board/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/board/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/./include/header.jsp", Long.valueOf(1692092545531L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <title>게시판을 만들어 보자</title>\r\n");
      out.write("    \r\n");
      out.write("	<!--개인 디자인 추가-->\r\n");
      out.write("    <link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("    \r\n");
      out.write("	<!-- Bootstrap CSS -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3\" crossorigin=\"anonymous\">\r\n");
      out.write("	<!-- CDN SCRIPT 추가영역 -->\r\n");
      out.write(" 	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("        <div class=\"head-div\">\r\n");
      out.write("        	<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><img class=\"header-img\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/css/logo.png\"></a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<section>\r\n");
      out.write("  <div class=\"container regist-container\">\r\n");
      out.write("    <p class=\"title\">게시판 등록</p>\r\n");
      out.write("    <div class=\"form-box\">\r\n");
      out.write("      <form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/regist\" method=\"post\" name=\"registForm\">\r\n");
      out.write("           \r\n");
      out.write("        <div class=\"writerPw\">\r\n");
      out.write("          <div class=\"writer-box\">\r\n");
      out.write("	        <div class=\"input-line writer-input\">\r\n");
      out.write("        	  <label for=\"writer\">작성자</label>\r\n");
      out.write("	          <input class=\"form-control\" type=\"text\" id=\"writer\" name=\"writer\" maxlength=\"10\" placeholder='최대 10자'>\r\n");
      out.write("	        </div>\r\n");
      out.write("           </div>\r\n");
      out.write("          <div class=\"pw-box\">\r\n");
      out.write("	        <div class=\"input-line pw-input\">\r\n");
      out.write("              <label for=\"password\">비밀번호</label>\r\n");
      out.write("              <input class=\"form-control\" type=\"password\" id=\"password\" name=\"password\" maxlength=\"15\" placeholder=\"영문, 숫자, 특수문자(@$!%*?&) 포함 8자~15자\">\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-line title-input\">\r\n");
      out.write("          <label for=\"title\">글제목</label>\r\n");
      out.write("          <input class=\"form-control\" type=\"text\" id=\"title\" name=\"title\" maxlength=\"50\" placeholder=\"50자 이내\">\r\n");
      out.write("          <span id=\"titleCheck\" class=\"title-fail\"></span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"input-line content-input\">\r\n");
      out.write("          <label for=\"content\">내용</label>\r\n");
      out.write("          <textarea class=\"form-control content\" id=\"content\" rows=\"10\" name=\"content\" maxlength=\"500\" oninput=checkContentLength()></textarea>\r\n");
      out.write("          <span id=\"contentLength\">0/500</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"titlefoot\">\r\n");
      out.write("          <button class=\"btn regist-btn btn-outline-primary\" id=\"registBtn\" type=\"button\">등록</button>\r\n");
      out.write("          <button type=\"button\" class=\"btn list-btn btn-outline-primary\" onclick=\"location.href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/'\">목록</button>\r\n");
      out.write("        </div>\r\n");
      out.write("      </form>\r\n");
      out.write("    </div>   \r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	const $writer = document.getElementById('writer');\r\n");
      out.write("	const $password = document.getElementById('password');\r\n");
      out.write("	const $title = document.getElementById('title');\r\n");
      out.write("	const $content = document.getElementById('content');\r\n");
      out.write("\r\n");
      out.write("	//작성자 검증\r\n");
      out.write("  $writer.addEventListener(\"input\", function() {\r\n");
      out.write("    const inputValue = $writer.value;\r\n");
      out.write("    // HTML 태그를 제거하고 공백을 포함한 총 10자리까지만 유지\r\n");
      out.write("    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("    if (sanitizedValue.length >= 10) {\r\n");
      out.write("      $writer.value = sanitizedValue.substring(0, 10);\r\n");
      out.write("      $writer.removeEventListener(\"input\", inputHandler);\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("  $writer.addEventListener(\"keyup\", function() {\r\n");
      out.write("	    const inputValue = $writer.value;\r\n");
      out.write("	    // HTML 태그를 제거하고 공백을 포함한 총 10자리까지만 유지\r\n");
      out.write("	    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("	    if (sanitizedValue.length >= 10) {\r\n");
      out.write("	      alert(\"작성자는 최대 10자까지만 입력 가능합니다.\");\r\n");
      out.write("	      $writer.value = sanitizedValue.substring(0, 10);\r\n");
      out.write("	      $writer.removeEventListener(\"input\", inputHandler);\r\n");
      out.write("	    }\r\n");
      out.write("	  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  function inputHandler() {\r\n");
      out.write("    const inputValue = $writer.value;\r\n");
      out.write("    // HTML 태그를 제거하고 공백을 포함한 총 10자리까지만 유지\r\n");
      out.write("    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("    if (sanitizedValue.length > 10) {\r\n");
      out.write("      $writer.value = sanitizedValue.substring(0, 10);\r\n");
      out.write("      $writer.removeEventListener(\"input\", inputHandler);\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  $writer.addEventListener(\"input\", inputHandler);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  //비밀번호 검증\r\n");
      out.write("  let isValidPassword = true;\r\n");
      out.write("  let isPasswordAlertShown = false;\r\n");
      out.write("\r\n");
      out.write("  $password.addEventListener('input', function(event) {\r\n");
      out.write("    const passwordRegex = /^(?=.*[a-zA-Z])(?=.*\\d)(?=.*[@$!%*?&])[A-Za-z\\d@$!%*?&]{8,15}$/;\r\n");
      out.write("    isValidPassword = passwordRegex.test($password.value);\r\n");
      out.write("    isPasswordAlertShown = false;\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  $password.addEventListener('blur', function(event) {\r\n");
      out.write("    if (!isValidPassword && !isPasswordAlertShown) {\r\n");
      out.write("      alert('비밀번호는 8자 이상 15자 이하의 영문, 숫자, 특수문자를 모두 포함해야 합니다.');\r\n");
      out.write("      $password.value = '';\r\n");
      out.write("      $password.focus();\r\n");
      out.write("      isPasswordAlertShown = true;\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  //제목 검증\r\n");
      out.write("  $title.addEventListener(\"input\", function() {\r\n");
      out.write("    const inputValue = $title.value;\r\n");
      out.write("    // HTML 태그를 제거하고 공백을 포함한 총 10자리까지만 유지\r\n");
      out.write("    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("    if (sanitizedValue.length >= 50) {\r\n");
      out.write("      alert(\"작성자는 50자까지만 입력 가능합니다.\");\r\n");
      out.write("      $title.value = sanitizedValue.substring(0, 50);\r\n");
      out.write("      $title.removeEventListener(\"input\", inputHandler);\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("//제목 검증\r\n");
      out.write("  $title.addEventListener(\"keyup\", function() {\r\n");
      out.write("    const inputValue = $title.value;\r\n");
      out.write("    // HTML 태그를 제거하고 공백을 포함한 총 10자리까지만 유지\r\n");
      out.write("    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("    if (sanitizedValue.length >= 50) {\r\n");
      out.write("      alert(\"작성자는 50자까지만 입력 가능합니다.\");\r\n");
      out.write("      $title.value = sanitizedValue.substring(0, 50);\r\n");
      out.write("      $title.removeEventListener(\"input\", inputHandler);\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write("\r\n");
      out.write("  function inputHandler() {\r\n");
      out.write("    const inputValue = $title.value;\r\n");
      out.write("    // HTML 태그를 제거하고 공백을 포함한 총 50자리까지만 유지\r\n");
      out.write("    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("    if (sanitizedValue.length >= 50) {\r\n");
      out.write("      $title.value = sanitizedValue.substring(0, 50);\r\n");
      out.write("      $title.removeEventListener(\"input\", inputHandler);\r\n");
      out.write("      alert(\"제목은 50자까지만 입력 가능합니다.\");\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("\r\n");
      out.write("  $title.addEventListener(\"input\", inputHandler);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  //내용 검증  \r\n");
      out.write("  $content.addEventListener(\"input\", function(event) {\r\n");
      out.write("    const inputValue = $content.value;\r\n");
      out.write("    // HTML 태그를 제거하고 정제된 값의 길이를 체크\r\n");
      out.write("    const sanitizedValue = inputValue.replace(/<\\/?[^>]+(>|$)/g, \"\");\r\n");
      out.write("    if (sanitizedValue.length >= 500) {\r\n");
      out.write("      $content.value = sanitizedValue.substring(0, 500);\r\n");
      out.write("      event.preventDefault();\r\n");
      out.write("      alert(\"내용은 최대 500자입니다.\");\r\n");
      out.write("    }\r\n");
      out.write("  });\r\n");
      out.write(" \r\n");
      out.write(" $content.addEventListener('keyup', function(event) {\r\n");
      out.write("    if ($content.value.length >= 500 && !event.ctrlKey) {\r\n");
      out.write("      $content.value = $content.value.slice(0, 500);\r\n");
      out.write("      checkContentLength();\r\n");
      out.write("      alert('내용은 최대 500자입니다.');\r\n");
      out.write("    } else {\r\n");
      out.write("      checkContentLength();\r\n");
      out.write("    }\r\n");
      out.write("  }); \r\n");
      out.write(" \r\n");
      out.write("  //내용 글자수\r\n");
      out.write("  function checkContentLength() {\r\n");
      out.write("    const contentLength = $content.value.length;\r\n");
      out.write("    document.getElementById('contentLength').textContent = $content.value.length + '/500';\r\n");
      out.write("  } \r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	document.getElementById('registBtn').addEventListener('click', function() {\r\n");
      out.write("		const form = document.forms['registForm'];\r\n");
      out.write("	    if (form.writer.value.trim() == '') {\r\n");
      out.write("	      alert('작성자를 입력하세요.');\r\n");
      out.write("	      form.writer.focus();\r\n");
      out.write("	    } else if(form.password.value.trim() =='') {\r\n");
      out.write("	      alert('비밀번호를 입력하세요.');\r\n");
      out.write("	   form.password.focus();\r\n");
      out.write("	    } else if (form.title.value.trim() ==''){\r\n");
      out.write("	      alert('제목을 입력하세요.');\r\n");
      out.write("	      form.title.focus();\r\n");
      out.write("	    } else if (form.content.value.trim() ==''){\r\n");
      out.write("	      alert('글 내용을 입력하세요.');\r\n");
      out.write("	      form.content.focus();\r\n");
      out.write("	    } else {\r\n");
      out.write("	      form.submit();\r\n");
      out.write("	    }\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js\" integrity=\"sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js\" integrity=\"sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    \r\n");
      out.write("<footer>\r\n");
      out.write("    <div class=\"copyright\">\r\n");
      out.write("        <span>©MYBOARD. ALL RIGHTS RESERVED</span>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("<!-- //footer -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
